# Generated by Django 5.0.6 on 2024-07-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=5)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
